separate wrapper function
vanvalenlab/kiosk-redis-consumer pull request #131
Opened 2020-09-18 20:16 UTC by ngreenwald

This provides a way for us to modify the post-processing params that are sent to the consumer.

Let me know if you think it would be better to have this somewhere else before I start moving forward

2020-09-21 19:21 UTC, willgraf requested changes
I think the consumer itself is still using `multiplex_postprocess` instead of the new value.

2020-09-21 19:21 UTC, willgraf commented on redis_consumer/processing.py
> +        nuclear_kwargs['radius'] = 5
Is `radius` the only one we want to default?

2020-09-21 20:45 UTC, ngreenwald commented
It's the only one that's different from the defaults in deepcell_toolbox.
Should we move all of the defaults to here?

On Mon, Sep 21, 2020 at 12:22 PM willgraf <notifications@github.com> wrote:

> *@willgraf* requested changes on this pull request.
>
> I think the consumer itself is still using multiplex_postprocess instead
> of the new value.
> ------------------------------
>
> In redis_consumer/processing.py
> <https://github.com/vanvalenlab/kiosk-redis-consumer/pull/131#discussion_r492292116>
> :
>
> > +    if whole_cell_kwargs is None:
> +        whole_cell_kwargs = {}
> +        whole_cell_kwargs['radius'] = 5
> +
> +    if nuclear_kwargs is None:
> +        nuclear_kwargs = {}
> +        nuclear_kwargs['radius'] = 5
>
> Is radius the only one we want to default?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vanvalenlab/kiosk-redis-consumer/pull/131#pullrequestreview-492911327>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADJB47NPTWVYYQLSJFR4VYDSG6RVZANCNFSM4RSO57HA>
> .
>

2020-09-21 20:45 UTC, ngreenwald commented
Actually nevermind, I'm going to update them with the newest
post-processing values, so I'll update all of them, and set the defaults
here. Will make things easier to update moving forward.

On Mon, Sep 21, 2020 at 1:44 PM Noah Greenwald <noahfgreenwald@gmail.com>
wrote:

> It's the only one that's different from the defaults in deepcell_toolbox.
> Should we move all of the defaults to here?
>
> On Mon, Sep 21, 2020 at 12:22 PM willgraf <notifications@github.com>
> wrote:
>
>> *@willgraf* requested changes on this pull request.
>>
>> I think the consumer itself is still using multiplex_postprocess instead
>> of the new value.
>> ------------------------------
>>
>> In redis_consumer/processing.py
>> <https://github.com/vanvalenlab/kiosk-redis-consumer/pull/131#discussion_r492292116>
>> :
>>
>> > +    if whole_cell_kwargs is None:
>> +        whole_cell_kwargs = {}
>> +        whole_cell_kwargs['radius'] = 5
>> +
>> +    if nuclear_kwargs is None:
>> +        nuclear_kwargs = {}
>> +        nuclear_kwargs['radius'] = 5
>>
>> Is radius the only one we want to default?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/vanvalenlab/kiosk-redis-consumer/pull/131#pullrequestreview-492911327>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADJB47NPTWVYYQLSJFR4VYDSG6RVZANCNFSM4RSO57HA>
>> .
>>
>

2020-09-21 20:52 UTC, willgraf commented
Yeah I think it makes sense to add all the values here so they're easier to tweak moving forward.

2020-09-22 16:55 UTC, ngreenwald commented
Okay, I updated it so there are defaults for all of them. 

Currently, the consumer post-processing function doesn't take additional arguments. This doesn't matter right now, since there's no way for users to control any of the post-processing parameters. Eventually, we might want to add that option to the ImageJ app or deepcell.org. When then happens, we'd need to add a way for the base post-processing class to handle additional arguments. 

However, since right now this doesn't exist, I set it up so that the 'defaults' are always used.

2020-09-22 17:53 UTC, willgraf approved these changes
This looks good, but I'd like to test the consumers out before we merge it.

2020-09-22 18:53 UTC, ngreenwald commented
Yup, deepcell.org and ImageJ both gave good looking results

2020-09-22 19:08 UTC, merged