Adding Polaris consumer
vanvalenlab/kiosk-redis-consumer pull request #181
Opened 2022-01-21 22:28 UTC by elaubsch

Adding Polaris consumer and tests

2022-01-21 23:33 UTC, msschwartz21 requested changes
I left some comments for you to look at, but my big picture concern is to take a second look at the assumptions regarding data shape in `PolarisConsumer._consume`. My impression is that you are assuming that you are going to get a 2d image with a batch dimension added by `get_image`. Is that assertion enforced somewhere else in the code? Have you tried uploading data with non-standard dimensions to see how its tolerated?

2022-01-22 00:31 UTC, elaubsch commented on requirements.txt
> +git+git://github.com/vanvalenlab/deepcell-spots@postcode_dependency
There are currently dependency issues with pip installing `deepcell_spots`. I'm going to pin the `deepcell-spots` version to a particular [commit](https://github.com/vanvalenlab/deepcell-spots/commit/c1d5314741dbebf00867ee69ed700891283377f7).

2022-01-22 00:46 UTC, elaubsch commented on redis_consumer/consumers/polaris_consumer.py
> +        scale = 1
I added the 100x option hoping to suggest that people upload 100x images, because the frontend sets the resolution dropdown to 100x automatically for the Polaris job card. `image_mpp` is not currently behaving as expected for the spot detection model, so I'm actually going to remove this line that sets `scale` to 1.

2022-01-23 01:25 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +        scale = 1
Can we check and see if Tom could make it possible to disable the channel and scale menus on the frontend?

2022-01-26 21:35 UTC, elaubsch commented on redis_consumer/consumers/polaris_consumer.py
> +        scale = 1
The scale menu has been disabled, I think we should leave the channel menu for now because I'm currently working on adding a cytoplasm channel to the app for singleplex FISH data

2022-01-26 22:51 UTC, elaubsch commented on redis_consumer/consumers/polaris_consumer.py
> +
Resulting image dimensions will always be (batch, x, y, channel) where channel is always 1. If 2D image is uploaded, batch and channel dimensions of 1 are added. If multi-batch image is uploaded, channel dimension of 1 is added. If multi-channel image is uploaded, channel dimension will be move to be batch dimension and channel dimension of 1 added. As is, the consumer (and spot model) cannot handle images multi-batch, multi-channel images.

2022-01-26 22:59 UTC, msschwartz21 requested changes
This is really close! Thanks for being so patient with all the questions and double-checks. Mostly what is left here are style-related comments, but I'm essentially ready to approve.

2022-01-26 22:59 UTC, msschwartz21 commented on Dockerfile
> +RUN apt-get update && apt-get install -y git
```suggestion
RUN apt-get install -y git
```

We don't need to update again since we call update in line 30. We could consolidate the git install with the others, but given that we will eventually get rid of the git dependency I'm ok with keeping it as a separate line.

2022-01-26 22:59 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +        scale = 1
Can we delete this line?

```suggestion
```

2022-01-26 22:59 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +            channels = None
`dict.get` returns None by default so consider this as an alternative:
```suggestion
        channels = hvals.get('channels')
        if channels:
            channels = [int(c) for c in hvals.get('channels').split(',')]
```

2022-01-26 22:59 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +        results = app.predict(image, batch_size=batch_size, threshold=0.99,
Do you expect this threshold value to change? For other models we have exposed parameters like this in `settings.py` so that they can be easily updated if needed

2022-01-26 22:59 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +            channels = None
If we get rid of the channel drop down, do we still need any of this code?

2022-01-26 22:59 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +
If you can confirm that the error message for multi-channel/multi-batch is informative, then I am happy with this section of code.

2022-01-26 23:08 UTC, elaubsch commented on redis_consumer/consumers/polaris_consumer.py
> +            channels = None
The other consumers all have this code, do you want to update it for all of them to be consistent?

2022-01-26 23:22 UTC, msschwartz21 commented on redis_consumer/consumers/polaris_consumer.py
> +            image = np.expand_dims(image, axis=[-1])
Let's add an else ValueError here specifying the dimension restrictions. Something like "data with shape x was uploading, but the Polaris application only supports multi channel or multi batch data.

2022-01-27 02:35 UTC, msschwartz21 approved these changes

2022-01-27 05:35 UTC, merged